defmodule Genie.Repo.Migrations.Slice1DomainFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :name, :text
      add :role, :text, null: false, default: "member"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :org_id, :uuid
    end

    create table(:turns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id, :uuid, null: false
    end

    create table(:sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:turns) do
      modify :session_id,
             references(:sessions,
               column: :id,
               name: "turns_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sessions) do
      add :title, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :org_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:organisations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:users) do
      modify :org_id,
             references(:organisations,
               column: :id,
               name: "users_org_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sessions) do
      modify :org_id,
             references(:organisations,
               column: :id,
               name: "sessions_org_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "sessions_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organisations) do
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organisations, [:slug], name: "organisations_unique_slug_index")

    create table(:audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :uuid
      add :lamp_id, :text
      add :intent_name, :text
      add :actor_id, :uuid
      add :trace_id, :text
      add :oban_job_id, :bigint
      add :result, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :key_hash, :text, null: false
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop table(:api_keys)

    drop table(:audit_logs)

    drop_if_exists unique_index(:organisations, [:slug], name: "organisations_unique_slug_index")

    alter table(:organisations) do
      remove :inserted_at
      remove :slug
      remove :name
    end

    drop constraint(:sessions, "sessions_org_id_fkey")

    drop constraint(:sessions, "sessions_user_id_fkey")

    alter table(:sessions) do
      modify :user_id, :uuid
      modify :org_id, :uuid
    end

    drop constraint(:users, "users_org_id_fkey")

    alter table(:users) do
      modify :org_id, :uuid
    end

    drop table(:organisations)

    alter table(:sessions) do
      remove :user_id
      remove :org_id
      remove :updated_at
      remove :inserted_at
      remove :title
    end

    drop constraint(:turns, "turns_session_id_fkey")

    alter table(:turns) do
      modify :session_id, :uuid
    end

    drop table(:sessions)

    drop table(:turns)

    alter table(:users) do
      remove :org_id
      remove :inserted_at
      remove :role
      remove :name
    end
  end
end
