defmodule Genie.Repo.Migrations.Slice6Conductor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lamp_actions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lamp_id, :text, null: false
      add :endpoint_id, :text, null: false
      add :params, :map
      add :actor_id, :uuid
      add :session_id, :uuid
      add :requires_approval, :boolean
      add :status, :text
      add :oban_job_id, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:lamp_actions)
  end
end
