defmodule Genie.Repo.Migrations.Slice3LampRegistry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lamp_registry, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lamp_id, :text, null: false
      add :org_id, :uuid
      add :xml_source, :text, null: false
      add :parsed_definition, :map, null: false
      add :enabled, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:lamp_registry, [:lamp_id], name: "lamp_registry_unique_lamp_id_index")
  end

  def down do
    drop_if_exists unique_index(:lamp_registry, [:lamp_id],
                     name: "lamp_registry_unique_lamp_id_index"
                   )

    drop table(:lamp_registry)
  end
end
